name: CI pipeline using called workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'examples/**'

jobs:
  code_analyze:
      uses: kishore3github/github-actions/.github/workflows/code_scanning.yaml@main
      with:
        language: 'java'
        version: '17'
        distribution: 'adopt'
      secrets:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build_and_push_image_to_dockerhub:
    uses: kishore3github/github-actions/.github/workflows/java-ci.yaml@main
    with:
      repoName: ${{ github.repository }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
