name: Build Gradle Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '40 9 * * *' # 3:10 PM IST (IST is UTC+5:30, so 15:10 IST = 09:40 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Use GitHub Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "The secret is $MY_SECRET" >> var.log
          cat var.log

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-example-all
          path: build/libs/gradle-example-all.jar

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results

  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run code coverage
        run: ./gradlew jacocoTestReport

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco