name: CI pipeline using called workflow

on:
  push:
    branches:
      - master

jobs:
  Build_and_push_image_to_dockerhub:
    uses: kishore3github/github-actions/.github/workflows/java-ci.yaml@main
    with:
        repoName: ${{ github.repository }}
    # secrets:
    #   EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}

