name: Build Gradle Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '40 9 * * *' # 3:10 PM IST (IST is UTC+5:30, so 15:10 IST = 09:40 UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Use GitHub Secret
        env:
          MY_SECRET: ${{ vars.DEMO_VAR }}
        run: |
          echo "The secret is $MY_SECRET" >> var.log
          cat var.log

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-example-all
          path: build/libs/gradle-example-all.jar