name: CI pipeline using called workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - 'examples/**'

jobs:
  Build_and_push_image_to_dockerhub:
    uses: kishore3github/github-actions/.github/workflows/java-ci.yaml@main
    with:
        repoName: ${{ github.repository }}
    secrets:
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
