name: Code Quality and Security Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [sonarcloud, semgrep]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK (only for SonarCloud)
        if: matrix.tool == 'sonarcloud'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Install SonarScanner
        run: |
          # Download the latest version of SonarScanner
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"

      - name: SonarCloud Scan
        if: matrix.tool == 'sonarcloud'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization="kishore3github" \
            -Dsonar.projectKey="kishore3github_gradle-example" \
            -Dsonar.sources="src" \
            -Dsonar.host.url="https://sonarcloud.io" 

      - name: Run Semgrep
        if: matrix.tool == 'semgrep'
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'
