name: Code Quality and Security Analysis

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [sonarcloud, semgrep]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK (only for SonarCloud)
        if: matrix.tool == 'sonarcloud'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Verify Java Version
        if: matrix.tool == 'sonarcloud'
        run: java -version

      - name: Print JAVA_HOME and PATH
        if: matrix.tool == 'sonarcloud'
        run: |
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Cache SonarCloud scanner
        uses: actions/cache@v2
        with:
          path: sonar-scanner-4.8.0.2856-linux
          key: sonar-scanner-${{ runner.os }}-${{ hashFiles('**/sonar-scanner.zip') }}
          restore-keys: |
            sonar-scanner-${{ runner.os }}-

      - name: Install SonarCloud Scanner
        run: |
          unzip sonar-scanner.zip
          echo "SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.8.0.2856-linux" >> $GITHUB_ENV
          echo "$SONAR_SCANNER_HOME/bin" >> $GITHUB_PATH

      # - name: Install SonarScanner
      #   if: matrix.tool == 'sonarcloud'
      #   run: |
      #     # Download the latest version of SonarScanner
      #     curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      #     unzip sonar-scanner.zip -d $HOME
      #     echo "$HOME/sonar-scanner-5.1.0.4882-linux/bin" >> $GITHUB_PATH

      - name: Verify SonarScanner Installation
        if: matrix.tool == 'sonarcloud'
        run: |
          which sonar-scanner || echo "SonarScanner is not installed in the PATH."
          sonar-scanner -v || echo "Unable to retrieve SonarScanner version."

      - name: SonarCloud Scan
        if: matrix.tool == 'sonarcloud'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # export JAVA_HOME=/opt/hostedtoolcache/Java_Adopt_jdk/17.0.13-11/x64
          # export PATH=$JAVA_HOME/bin:$PATH
          sonar-scanner \
            -Dsonar.organization="kishore3github" \
            -Dsonar.projectKey="kishore3github_gradle-example" \
            -Dsonar.sources="src" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login=$SONAR_TOKEN 

      - name: Run Semgrep
        if: matrix.tool == 'semgrep'
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/ci'
