name: Gradle Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew shadowJar
        
      - name: List build artifacts
        run: ls -al build/libs
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: gradle-image:latest
         # tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest
        
      - name: Run the application
        run: java -jar build/libs/gradle-example-all.jar
